global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - /etc/prometheus/prometheus-rules.yml

alerting:
  alertmanagers:
    - static_configs:
        - targets: ["alertmanager:9093"]

scrape_configs:
  - job_name: gateway-api
    metrics_path: /metrics
    static_configs:
      - targets: ["gateway-api:8000"]

  - job_name: recommendation-service
    metrics_path: /metrics
    static_configs:
      - targets: ["recommendation-service:8001"]

  - job_name: interaction-ingest-service
    metrics_path: /metrics
    static_configs:
      - targets: ["interaction-ingest-service:8002"]

  - job_name: content-worker
    metrics_path: /metrics
    static_configs:
      - targets: ["content-worker:9101"]

  - job_name: feature-worker
    metrics_path: /metrics
    static_configs:
      - targets: ["feature-worker:9102"]

  - job_name: model-trainer
    metrics_path: /metrics
    static_configs:
      - targets: ["model-trainer:9103"]

  - job_name: postgres
    metrics_path: /metrics
    static_configs:
      - targets: ["postgres-exporter:9187"]

  - job_name: redis-state
    metrics_path: /metrics
    static_configs:
      - targets: ["redis-exporter:9121"]

  - job_name: redis-cache
    metrics_path: /metrics
    static_configs:
      - targets: ["redis-cache-exporter:9121"]

  - job_name: kafka
    metrics_path: /metrics
    static_configs:
      - targets: ["kafka-exporter:9308"]

  - job_name: flink
    metrics_path: /metrics
    static_configs:
      - targets: ["flink-jobmanager:9249", "flink-taskmanager:9249"]
