{{- if and .Values.secrets.create (not .Values.secrets.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "video-commerce.secretName" . }}
  labels:
    {{- include "video-commerce.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.secrets.keys.apiApiKey }}: {{ .Values.secrets.values.apiApiKey | quote }}
  {{ .Values.secrets.keys.internalServiceKey }}: {{ .Values.secrets.values.internalServiceKey | quote }}
  {{ .Values.secrets.keys.redisPassword }}: {{ .Values.secrets.values.redisPassword | quote }}
  {{ .Values.secrets.keys.redisCachePassword }}: {{ .Values.secrets.values.redisCachePassword | quote }}
  {{ .Values.secrets.keys.databaseUrl }}: {{ .Values.secrets.values.databaseUrl | quote }}
  {{ .Values.secrets.keys.objectStorageAccessKeyId }}: {{ .Values.secrets.values.objectStorageAccessKeyId | quote }}
  {{ .Values.secrets.keys.objectStorageSecretAccessKey }}: {{ .Values.secrets.values.objectStorageSecretAccessKey | quote }}
  {{ .Values.secrets.keys.jwtSharedSecret }}: {{ .Values.secrets.values.jwtSharedSecret | quote }}
  {{- range $key, $value := .Values.secrets.extraStringData }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
